### ISSUE TITLE
Publish new sphinx-csv-filter release?

### ISSUE THREAD

**Issue by op-ct** [crate/sphinx_csv_filter#23]
Would it be possible to publish a new release of sphinx-csv-filter?

The latest `pip install` pulls down is 0.2.0, but the `:include:` filter was introduced after that.

**Comment by christianbader** [comment]
Version 0.3.0 is available on `pypi` https://pypi.org/project/sphinx-csv-filter/

**Comment by op-ct** [comment]
Thanks, @christianbader!
